#!/bin/sh

exec 2>&1
sv check weston > /dev/null || exit 1
sv check mira-ui > /dev/null || exit 1
sv check go-librespot > /dev/null || exit 1

export XDG_RUNTIME_DIR="/run/wayland/"
export XDG_CACHE_HOME="/var/cache"
export BREAKPAD_DUMP_LOCATION="/var/cache/chrome_storage/Crash Reports"

rm -rf /var/cache/chrome_storage/Default/Cache \
  "/var/cache/chrome_storage/Default/Code Cache" \
  /var/cache/chrome_storage/Default/GPUCache 2>/dev/null

rm -f /var/cache/chrome_storage/Singleton* 2>/dev/null

ls -1t "$BREAKPAD_DUMP_LOCATION"/*.dmp 2>/dev/null | tail -n +4 | while read -r f; do
  rm -f "$f"
done

exec /usr/bin/chromium-browser/chrome --no-sandbox --in-process-gpu --remote-debugging-port=2222 --user-data-dir=/var/cache/chrome_storage --disk-cache-size=52428800 --kiosk --disable-pinch --allow-file-access-from-files --ignore-certificate-errors --enable-experimental-web-platform-features --app=http://localhost:80 > /dev/null 2>&1
